### ISSUE TITLE
Support Cypress 9.0.0?

### ISSUE THREAD

**Issue by crs1138** [tschortsch/cypress-wp-test-utils#8]
I wanted to use your package with the latest Cypress 9.0.0, but it wouldn't install unless I downgraded the Cypress version.

```
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"5.x || 6.x || 7.x || 8.x" from cypress-wp-test-utils@0.4.0
```

**Comment by tschortsch** [comment]
cypress 9.x is supported in v0.5.0 (https://github.com/tschortsch/cypress-wp-test-utils/releases/tag/0.5.0) of the package.
